### ISSUE TITLE
About `Real_FITS.py`

### ISSUE THREAD

**Issue by zhixuanli** [VEWOXIC/FITS#11]
Dear authors, 

Thanks for your wonderful work FITS and releasing the codes!

I'm trying to use the `Real_FITS.py` for training on NVIDIA 4090 GPU. However, seems like the model in this file cannot be directly used by replacing the model name in the scripts. This is because this file is not included in `exp_main_F.py`.

Moreover, the `Real_FITS.py` itself is not very complete. For example, `self.output_len` in Line 70 is missing in the `_init_` function of this class.

Could you please make the training of `Real_FITS.py` feasible by completing some missing details?

Thanks for your time!

**Comment by VEWOXIC** [comment]
Sure, I will check! 

btw, can you run with the above fix you mentioned?

**Comment by VEWOXIC** [comment]
Hi, the code have been updated and validated! Please check!

**Comment by zhixuanli** [comment]
> Sure, I will check!
> 
> btw, is it working with the above fix you mentioned?

Yes, it works with the mentioned fix.

Thank you for your really quick response!!! 

I have no more questions. And I really like your new paper which is a very innovative new setting. 

Warm regards!

**Comment by VEWOXIC** [comment]
Thanks for your support and recognition! 

I will close this issue if no more questions. Please feel free to reopen it.

Please feel free to reach out if you want some further discussion.
