### ISSUE TITLE
Question about bugs in test dataloader

### ISSUE THREAD

**Issue by tokaka22** [VEWOXIC/FITS#15]
Sorry to bother you again, could you tell me which paper by Luke Nicholas Darlow points out the bugs in the test dataloader? I've read some his papers including 2 EuroSysML’23 papers, but they don't seem to mention it.
Thank you!

**Comment by VEWOXIC** [comment]
Sorry, he did not mention it in any paper. He reached out to me in person.

**Comment by VEWOXIC** [comment]
If there is no further question, I will close this issue.

**Comment by tokaka22** [comment]
Thank you for your kind response!
