### ISSUE TITLE
Release Best Configurations for Electricity and Traffic Datasets 

### ISSUE THREAD

**Issue by ViswanathaReddyGajjala** [VEWOXIC/FITS#16]
Thank you for the great work! I was wondering if there are any plans to release the best configurations for the electricity and traffic datasets found in `scripts/FITS`.

**Comment by VEWOXIC** [comment]
Thanks for your recognition! Sorry that we did not directly provide the best training script. Maybe you can find the best parameter combination by inspecting the logs in [the logs](https://github.com/VEWOXIC/FITS/tree/a1ab5c373539b2be311cd7c48826e06052a62b3b/logs/fixFITS).

**Comment by VEWOXIC** [comment]
If there is no more question, I will close this issue. Please feel free to reopen it.
