### ISSUE TITLE
Could you update MAE for previous models affected by the 'drop_last=True' bug?

### ISSUE THREAD

**Issue by JingzheShi** [VEWOXIC/FITS#2]
Dear Authors:

Impressed by the effectiveness and insightfull idea of your work!

Thanks a lot for pointing out the drop_last=True bug! I am interested in the area of multivariable time series forecasting and I think this is a common bug for many repos.

I started this issue wondering if you could update MAE for previous models affected by the bug at the same time, so that I do not need to run the experiments myself to know the accurate result (to be compared in later works)?

Because you have updated MSE for previous sota models, I think perhaps it would not be too complicated for you to update MAE at the same time (as MSE, MAE results are usually given together in experiments). Anyway, I have been very grateful so far for your giving detailed description of the bug and reported corrected MSE results for previous models. Thanks!

**Comment by VEWOXIC** [comment]
We have uploaded the full training log. Maybe you can check it out? I think the mae should be at the last line of each log file. 

And I will check if there's any other logs we did not upload here. 

Thanks!
