### ISSUE TITLE
Question about the code 

### ISSUE THREAD

**Issue by csguoh** [VEWOXIC/FITS#3]
Hi, authors
Thx for this incredible work! I have a question about the code implementation of [this line](https://github.com/VEWOXIC/FITS/blob/aba1737ce1efcaf11d3f36e23e789fcc33207552/models/Real_FITS.py#L59) in `Real_FITS.py`. I can not figure out why use the `real+ imag` / `real-imag` to generate the results. Why not directly generate the real or image with the corresponding layer? I would appreciate if you could explain this. 

Thx ;D

**Comment by VEWOXIC** [comment]
Thanks for being interested in our work! XD

FITS fundamentally works as multiplying a complex vector $X$ by a complex weight matrix $W$. 

$$
Y=X*W
$$

However, if we break it down to real number computation, it should be:

$$
Y_real = X_real*W_real - X_imag*W_imag
Y_imag = X_real*W_imag + X_imag*W_real
$$

That is exactly what we do in the FITS_real, simulating this break down. 

Hope this can help you.

**Comment by VEWOXIC** [comment]
I have added a comment in real_FITS.py for this! :D

**Comment by csguoh** [comment]
Thx for your detailed explanation!
