### ISSUE TITLE
Have there been any experiments on classification task?

### ISSUE THREAD

**Issue by robustor123** [VEWOXIC/FITS#5]
i could find experiments about forecasting and anomaly detection in your paper.
Have there been any experiments on classification task?

**Comment by VEWOXIC** [comment]
Sorry, we did not perform the classification with FITS. We did not come up with a way to formulate the classification task as frequency interpolation.

**Comment by VEWOXIC** [comment]
If there is no further question. I will close this issue. Please feel free to reopen it.
