### ISSUE TITLE
About applying nn.Linear() to complex fft?

### ISSUE THREAD

**Issue by Joeland4** [VEWOXIC/FITS#7]
Dear author, I can't understand the difference between directly using nn.Linear to complex tensor after FFT and separately two to real, image parts?  I don't know why the nn.Linear can be directly applied to FFT, what is the outcome, a linear transformation of Amplitudes?

**Comment by VEWOXIC** [comment]
Hi, they are the same. We also provide a version of FITS with real-valued linear to simulate the complex-valued operation. We have validated that they both produce exactly the same result. 

As for why, the complex valued linear layer is just for extending the original FFT spectrum. Thus, its output is also a complex valued spectrum. It not only output amplitude, but also managed to handle the phase shifting of each frequency components.

**Comment by VEWOXIC** [comment]
If there is no further question, I will close this issue. Please feel free to reopen it!

**Comment by Joeland4** [comment]
Thank you for your help ！
