### ISSUE TITLE
Difference between exp_main.py and exp_main_F.py

### ISSUE THREAD

**Issue by huangst21** [VEWOXIC/FITS#8]
Hi, thanks for your valuable work. Can you explain the difference between exp_main.py and exp_main_F.py. Which file should I run to get the correct results?

**Comment by VEWOXIC** [comment]
Hi, please run the exp_main_F or FITS. Or you can just follow the scripts provided in the scripts folder.

**Comment by VEWOXIC** [comment]
If there is no more further question, I will close this issue. Please feel free to reopen it!
